### ISSUE TITLE
Cannot build the examples due to package not found error.

### ISSUE THREAD

**Issue by menakaj** [mathetake/proxy-wasm-go#1]
Hi,

I am trying to experiment with the go SDK and encountered following issue when building the examples.

```
$tinygo build -o wasm.wasm -wasm-abi=generic -target wasm ./main.go && docker-compose up | grep OnTick

/main.go: cannot find package "github.com/mathetake/proxy-wasm-go/runtime" in any of:
	/usr/local/go/src/github.com/mathetake/proxy-wasm-go/runtime (from $GOROOT)
	/Users/menakajayawardena/go/src/github.com/mathetake/proxy-wasm-go/runtime (from $GOPATH)
```

Could you please let me know if anything to be done to overcome this? 
Thanks

**Comment by mathetake** [comment]
@menakaj Hi, thank you for playing with this.

Looks like you did not place this sdk on `${GOPATH}/github.com/mathetake/proxy-wasmgo` .

Tinygo does NOT support gomod so you need to do so.

**Comment by menakaj** [comment]
Thank you very much @mathetake.  I will close this issue since my question is answered.
