### ISSUE TITLE
Is there an update?

### ISSUE THREAD

**Issue by wansuiye** [mathetake/proxy-wasm-go#3]
This is a great project and I have been studying wasm-go recently. Is there any update? thanks

**Comment by mathetake** [comment]
@wansuiye Hi, thank you for taking a look at my project.

Actually proxy-wasm's official speci is currently under review: https://github.com/proxy-wasm/spec/pull/1 and it's going to be take much more time to be merged.

That being said, I will not going to make any BIG changes to this SDK until it's merged. But any PR and comment is welcome

Thank you!

**Comment by mathetake** [comment]
@wansuiye FYI, I've just started working on this sdk to get this integrated with [GetEnvoy's](https://www.getenvoy.io/) extension feature as in Rust https://www.getenvoy.io/tutorials/getting-started-http-filter-rust/ .

Stay tuned on https://twitter.com/Tetrateio for the updates! thanks
