### ISSUE TITLE
concurrent issue

### ISSUE THREAD

**Issue by haorenfsa** [mathetake/proxy-wasm-go#4]
https://github.com/mathetake/proxy-wasm-go/blob/af5a4332add6516ec3d969c9f698ab0ab09ba92e/runtime/vmstate.go#L18

Would there be concurrent risk since native map in golang doesn't support concurrent write ?

**Comment by mathetake** [comment]
Nope, WASM VM is created per envoy worker threads as being documented here https://github.com/proxy-wasm/spec/blob/2960baa9df97c878608daa5dbf6b4ffca97b17ab/docs/WebAssembly-in-Envoy.md#high-level-overview
